CREATE TABLE LINEORDER (
  LO_ORDERKEY INTEGER,
  LO_LINENUMBER INTEGER,
  LO_CUSTKEY INTEGER,
  LO_PARTKEY INTEGER,
  LO_SUPPKEY INTEGER,
  LO_ORDERDATE INTEGER,
  LO_ORDERPRIORITY TEXT,
  LO_SHIPPRIORITY TEXT,
  LO_QUANTITY INTEGER,
  LO_EXTENDEDPRICE REAL,
  LO_ORDTOTALPRICE REAL,
  LO_DISCOUNT REAL,
  LO_REVENUE REAL,
  LO_SUPPLYCOST REAL,
  LO_TAX REAL,
  LO_COMMITDATE INTEGER,
  LO_SHPIMODE TEXT,
  PRIMARY KEY(LO_ORDERKEY, LO_LINENUMBER)
);

CREATE TABLE PART (
  P_PARTKEY TEXT PRIMARY KEY,
  P_NAME TEXT,
  P_MFGR TEXT,
  P_CATEGORY TEXT,
  P_BRAND1 TEXT,
  P_COLOR TEXT,
  P_TYPE TEXT,
  P_SIZE INTEGER,
  P_CONTAINER TEXT
);

CREATE TABLE SUPPLIER (
  S_SUPPKEY INTEGER PRIMARY KEY,
  S_NAME TEXT,
  S_ADDRESS TEXT,
  S_CITY TEXT,
  S_NATION TEXT,
  S_REGION TEXT,
  S_PHONE TEXT
);

CREATE TABLE CUSTOMER (
  C_CUSTKEY INTEGER PRIMARY KEY,
  C_NAME TEXT,
  C_ADDRESS TEXT,
  C_CITY TEXT,
  C_NATION TEXT,
  C_REGION TEXT,
  C_PHONE TEXT,
  C_MKTSEGMENT TEXT
);

CREATE TABLE DATE (
  D_DATEKEY INTEGER PRIMARY KEY,
  D_DATE TEXT,
  D_DAYOFTHEWEEK TEXT,
  D_MONTH TEXT,
  D_YEAR INTEGER,
  D_YEARMONTHNUM INTEGER,
  D_YEARMONTH TEXT,
  D_DAYNUMINWEEK INTEGER,
  D_DAYNUMINMONTH INTEGER,
  D_DAYNUMINYEAR INTEGER,
  D_MONTHNUMINYEAR INTEGER,
  D_WEEKNUMINYEAR INTEGER,
  D_SELLINGSEASON TEXT,
  D_LASTDAYINWEEKFL INTEGER,
  D_LASTDAYINMONTHFL INTEGER,
  D_HOLIDAYFL INTEGER,
  D_WEEKDAYFL INTEGER
);
